name: CI/CD

on:
  push:
    branches: [master, dev]

jobs:
  ci_cd:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use latest Node.js LTS
        uses: actions/setup-node@v3
        with:
          node-version: lts/*
          cache: npm
      - name: Install
        run: npm ci
      - name: Lint
        run: npm run ci-lint
      - name: Check code formatting
        run: npm run format-check
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: haphihung55/cinerate-api-server:latest
